name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install
          

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

      -   name: Set RapidAPI key environment variable
          run: echo "VITE_RAPID_API_KEY=${{ secrets.VITE_RAPID_API_KEY }}" >> $GITHUB_ENV
  
      -   name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
  
  deploy-proxy:
      name: Deploy Proxy
      needs: build
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
  
        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: '16.x'
  
        - name: Install dependencies
          run: |
            npm install
            npm install pm2
  
        - name: Set RapidAPI key environment variable
          run: echo "RAPIDAPI_KEY=${{ secrets.VITE_RAPID_API_KEY }}" >> $GITHUB_ENV
  
        - name: Start proxy server
          run: pm2 start ./server.js --name "proxy-server"
  
        - name: Wait for proxy server to start
          run: pm2 logs "proxy-server" | grep -q "Server started" && echo "Proxy server started successfully"
  
        - name: Stop proxy server
          run: pm2 stop "proxy-server"
  
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist