name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install http-proxy-middleware dotenv

      - name: Build project
        run: npm run build

      - name: Set RapidAPI key environment variable
        run: echo "VITE_RAPID_API_KEY=${{ secrets.VITE_RAPID_API_KEY }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  deploy-proxy:
    name: Deploy Proxy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install pm2

      - name: Set RapidAPI key environment variable
        run: echo "RAPIDAPI_KEY=${{ secrets.VITE_RAPID_API_KEY }}" >> $GITHUB_ENV

      - name: Start proxy server
        run: pm2 start src/setupProxy.jsx --name "proxy-server"

      - name: Wait for proxy server to start
        run: pm2 logs "proxy-server" | grep -q "Server started" && echo "Proxy server started successfully"

      - name: Stop proxy server
        run: pm2 stop "proxy-server"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist